#pragma once
#include "raylib.h"
#include "theme.h"
#include <vector>

// Pixel-art world assets generated by tools/make_world_art.py.
// Art is authored at 1x and drawn at PIXEL_SCALE with point filtering.
namespace WorldArt {
    inline constexpr float PIXEL_SCALE = 2.f;
    inline constexpr int BIOME_COUNT = 9;
    enum TileRow { ROW_CRUMBLING = 9, ROW_SPRING = 10, ROW_ICE = 11, ROW_GHOST = 12 };

    struct Assets {
        bool loaded = false;
        Texture2D tiles{};
        Texture2D items{};                   // 4 coin spin frames + 4 power-up orbs, 16x16
        Texture2D biome[BIOME_COUNT]{};      // [sky deco | far | near], each 240x400
        std::vector<Texture2D> skies;        // dithered gradient per theme
    };

    void Load(Assets &a, const std::vector<Theme> &themes);
    void Unload(Assets &a);

    // Platform strip at rect (top-aligned); tint alpha fades the whole strip.
    void DrawPlatform(const Assets &a, Rectangle rect, int row, Color tint);
    void DrawCoin(const Assets &a, Vector2 center, float animTime);
    void DrawPowerUp(const Assets &a, Vector2 center, int type, float animTime);
    void DrawSky(const Assets &a, int themeIndex, int w, int h, Color tint);
    // cameraY: world Y of camera target; layers scroll with parallax and tile vertically.
    void DrawBiomeLayers(const Assets &a, int biome, float cameraY, int w, int h, Color tint);

    // Axis-aligned pixel dot snapped to the art grid (for particles / ambient effects).
    inline void PixelDot(float x, float y, float size, Color c) {
        int s = (int)(size < 1.f ? 1.f : size) * 2;
        int px = ((int)x / 2) * 2, py = ((int)y / 2) * 2;
        DrawRectangle(px - s / 2, py - s / 2, s, s, c);
    }
}
